-- =============================================================================
--      FINAL DATABASE SCHEMA & FUNCTIONS FOR GEMINI ATTENDANCE SYSTEM
-- =============================================================================
-- This script sets up all necessary tables, functions, and security policies.
-- It is designed to be run once in the Supabase SQL Editor.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PART 1: EXTENSIONS & INITIAL SETUP
-- Enable PostGIS for geospatial data types and functions (for GPS locations).
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;


-- -----------------------------------------------------------------------------
-- PART 2: TABLE DEFINITIONS
-- Creating the core tables for the application.
-- -----------------------------------------------------------------------------

-- Table: employees
-- Stores profile information for each employee.
CREATE TABLE public.employees (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_id TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    department TEXT,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE public.employees IS 'Stores employee profile information. The employee_id is used for the QR code.';

-- Table: devices
-- Registers the trusted kiosk devices used for scanning.
CREATE TABLE public.devices (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    device_name TEXT NOT NULL,
    device_unique_id TEXT NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    location geography(POINT, 4326) NOT NULL, -- The fixed GPS location of the office where this device is installed.
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
COMMENT ON TABLE public.devices IS 'Registers trusted kiosk devices. The location is the ground-truth for verifying attendance location.';

-- Table: attendance_logs
-- Stores every check-in and check-out event with verification data.
CREATE TABLE public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id uuid REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
    device_id uuid REFERENCES public.devices(id) ON DELETE SET NULL,
    check_in_time TIMESTAMPTZ NOT NULL,
    check_in_photo_url TEXT,
    check_in_location geography(POINT, 4326),
    check_out_time TIMESTAMPTZ,
    check_out_photo_url TEXT,
    check_out_location geography(POINT, 4326),
    date DATE NOT NULL DEFAULT CURRENT_DATE
);
COMMENT ON TABLE public.attendance_logs IS 'Records each check-in and check-out event with photo and location verification.';

-- Add an index on the date column for faster querying in the admin panel.
CREATE INDEX idx_attendance_logs_date ON public.attendance_logs(date);


-- -----------------------------------------------------------------------------
-- PART 3: STORAGE BUCKET & POLICIES
--
-- IMPORTANT: You must first manually create a Storage Bucket named "attendance-photos"
-- in your Supabase project dashboard. Make it a PUBLIC bucket.
-- Then, run the policy scripts below.
-- -----------------------------------------------------------------------------

-- Policy: Allow authenticated users (which includes service roles used by Edge Functions)
-- to upload images into the "attendance-photos" bucket.
CREATE POLICY "Allow authenticated uploads"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'attendance-photos');

-- Policy: Allow anyone to read images from the bucket.
-- This makes it easy to display photos in the admin panel without complex signed URLs.
CREATE POLICY "Allow public read access"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'attendance-photos');


-- -----------------------------------------------------------------------------
-- PART 4: RPC (REMOTE PROCEDURE CALL) FUNCTIONS
-- These are the secure, server-side functions that your apps will call.
-- -----------------------------------------------------------------------------

-- Function: log_verified_attendance
-- The main function for the Kiosk App. Handles both check-in and check-out.
-- It is the single, secure entrypoint for logging attendance.
CREATE OR REPLACE FUNCTION public.log_verified_attendance(
    p_employee_id TEXT,
    p_device_unique_id TEXT,
    p_photo_url TEXT,
    p_longitude FLOAT,
    p_latitude FLOAT
)
RETURNS TEXT -- Returns a success message for the Kiosk UI
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    emp_id uuid;
    dev_id uuid;
    dev_office_location geography;
    log_id bigint;
    emp_full_name text;
    kiosk_current_location geography;
BEGIN
    -- Step 1: Find the employee and device from the provided IDs.
    SELECT id, full_name INTO emp_id, emp_full_name FROM public.employees WHERE employee_id = p_employee_id AND is_active = TRUE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Employee not found or is inactive.'; END IF;

    SELECT id, location INTO dev_id, dev_office_location FROM public.devices WHERE device_unique_id = p_device_unique_id AND is_active = TRUE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Device not registered or is inactive.'; END IF;

    -- Step 2: Create a geography point from the kiosk's current coordinates.
    kiosk_current_location := ST_SetSRID(ST_MakePoint(p_longitude, p_latitude), 4326);

    -- Step 3: SECURITY CHECK - Verify the kiosk is physically at the office (within a 50-meter radius).
    IF NOT ST_DWithin(kiosk_current_location, dev_office_location, 50) THEN
        RAISE EXCEPTION 'Verification Failed: Device is not at the registered office location.';
    END IF;

    -- Step 4: Check for an existing, open attendance log for this employee today.
    SELECT id INTO log_id FROM public.attendance_logs WHERE employee_id = emp_id AND date = CURRENT_DATE AND check_out_time IS NULL;

    -- Step 5: Perform the check-out or check-in operation.
    IF log_id IS NOT NULL THEN
        -- CHECK-OUT: An open log was found, so update it.
        UPDATE public.attendance_logs SET check_out_time = NOW(), check_out_photo_url = p_photo_url, check_out_location = kiosk_current_location WHERE id = log_id;
        RETURN 'Goodbye, ' || emp_full_name || '!';
    ELSE
        -- CHECK-IN: No open log was found, so create a new one.
        INSERT INTO public.attendance_logs (employee_id, device_id, check_in_time, check_in_photo_url, check_in_location, date)
        VALUES (emp_id, dev_id, NOW(), p_photo_url, kiosk_current_location, CURRENT_DATE);
        RETURN 'Welcome, ' || emp_full_name || '!';
    END IF;
END;
$$;


-- Function: get_attendance_summary
-- For the Admin Portal Dashboard. Provides key statistics for a given date.
CREATE OR REPLACE FUNCTION public.get_attendance_summary(
    p_date DATE
)
RETURNS TABLE (total_present BIGINT, total_on_time BIGINT, total_late BIGINT)
LANGUAGE sql STABLE
AS $$
    SELECT
        COUNT(*) AS total_present,
        COUNT(*) FILTER (WHERE check_in_time::time <= '09:05:00') AS total_on_time, -- On-time if before 9:05 AM
        COUNT(*) FILTER (WHERE check_in_time::time > '09:05:00') AS total_late
    FROM public.attendance_logs
    WHERE date = p_date;
$$;


-- -----------------------------------------------------------------------------
-- PART 5: ROW LEVEL SECURITY (RLS)
-- Enable RLS and define policies to protect data access.
-- -----------------------------------------------------------------------------

-- Enable RLS for all tables
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

-- POLICIES: For this system, we assume a logged-in admin should be able to see everything.
-- The Kiosk app will use the anon key but will only interact via the secure RPC function.

CREATE POLICY "Allow admin full access on employees" ON public.employees
FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow admin full access on devices" ON public.devices
FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow admin full access on attendance logs" ON public.attendance_logs
FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- NOTE: No INSERT policy is needed for `attendance_logs` for the Kiosk, because
-- the `log_verified_attendance` function is `SECURITY DEFINER`. It securely handles
-- the insertion on the server side, bypassing RLS for that specific, controlled action.

-- =============================================================================
--                        SCRIPT COMPLETE
-- =============================================================================